### PR TITLE
fix aabb

### PR DESCRIPTION
**Pull request by hbb1**
Fix issue of #15 

Still need some time for testing

### CODE REVIEW

**Comment by LinzhouLi** [comment]
Since the cutoff in `renderCUDA()` is 1/255, the accurate cutoff sigma value is $\sqrt{2*\log_2(255.0)}\approx 3.329$ but not 3. I try to fix the bug accordding to your AABB calculation https://github.com/hbb1/diff-surfel-rasterization/issues/15#issuecomment-2195228658.
when $R^2=9.0$, the AABB is not big enougth:
image

when $R^2=11.1$, the AABB is accurate:
image

**Comment by hbb1** [comment]
@LinzhouLi  Thank you for pointing out this. Yes, it is correct. the 1/255 is used for opacity * G(x) not just G(x). Using 3.3 for bounding box estimation seems too conservative since only less than 5% of Gaussians will have high opacity.  Let us keep the same for 3DGS, what do you think?

**Comment by hbb1** [comment]
Plus, when computing the normal map, pixels with accumulated alpha less than a threshold, e.g. 0.005, can be treated as the background color, resulting in a rendered contour resembling an eclipse. This will increase robustness when dealing with transparent region.

**Comment by LinzhouLi** [comment]
Thanks for explaination. I agree with you.

**Pull request merged**
